import { HospitalProfile } from '../types';

// Les 9 établissements ELSAN - Données fixes
export const HOSPITALS_DATA: Omit<HospitalProfile, 'match_percentage' | 'distance_km'>[] = [
  {
    id: 'SRO',
    name: 'Clinique SMR Supervaltech',
    location: 'Saint-Estève (66)',
    region_vibe: 'Moderne et dynamique, proche Perpignan',
    size: ['Grande'],
    specialty_focus: ['SSR', 'Rééducation', 'Réadaptation'],
    bio: '🏥 Établissement moderne au cœur des Pyrénées-Orientales. On allie innovation médicale et qualité de vie catalane. Nos équipes dynamiques adorent le soleil autant que l\'excellence !',
    leisure_activities: ['Plage à 20min', 'Randonnée', 'Culture catalane', 'Gastronomie'],
    work_rhythm: ['Équilibré', 'Pluridisciplinaire'],
    perks: ['Plateau technique moderne', 'Formation continue', 'Ambiance conviviale', 'Parking gratuit'],
    image_url: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=800&auto=format&fit=crop',
    video_url: 'https://www.youtube.com/watch?v=F_Sj8d94W2k',
  },
  {
    id: 'SPI',
    name: 'Clinique Saint-Pierre',
    location: 'Perpignan (66)',
    region_vibe: 'Historique, centre-ville, excellence',
    size: ['Moyenne'],
    specialty_focus: ['Chirurgie', 'Médecine', 'MCO'],
    bio: '⚕️ Au cœur de Perpignan depuis 1920. Nous mêlons tradition d\'excellence et modernité. Ambiance familiale, exigence médicale, et l\'accent du Sud en prime !',
    leisure_activities: ['Centre-ville', 'Festivals', 'Restaurants', 'Mer à 15km'],
    work_rhythm: ['Soutenu', 'Polyvalent'],
    perks: ['Réputation établie', 'Équipe expérimentée', 'Centre-ville', 'Spécialités variées'],
    image_url: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?q=80&w=800&auto=format&fit=crop',
    video_url: 'https://www.youtube.com/watch?v=F_Sj8d94W2k',
  },
  {
    id: 'SMI',
    name: 'Clinique Saint-Michel',
    location: 'Prades (66)',
    region_vibe: 'Nature, montagne, calme',
    size: ['Familiale'],
    specialty_focus: ['SSR', 'Gériatrie', 'Soins de suite'],
    bio: '🏔️ Nichée au pied du Canigou, notre clinique respire la sérénité. Pour ceux qui rêvent de soigner tout en respirant l\'air pur de la montagne. Ici, on prend le temps !',
    leisure_activities: ['Randonnée', 'Ski (hiver)', 'VTT', 'Patrimoine roman'],
    work_rhythm: ['Tranquille', 'Humain'],
    perks: ['Cadre exceptionnel', 'Petite équipe soudée', 'Proximité montagne', 'Qualité de vie'],
    image_url: 'https://images.unsplash.com/photo-1519817650390-64a93db51149?q=80&w=800&auto=format&fit=crop',
    video_url: 'https://www.youtube.com/watch?v=F_Sj8d94W2k',
  },
  {
    id: 'NDE',
    name: 'Polyclinique Méditerranée',
    location: 'Perpignan (66)',
    region_vibe: 'Familial, proximité',
    size: ['Moyenne'],
    specialty_focus: ['Chirurgie ambulatoire', 'Médecine', 'Imagerie'],
    bio: '🌊 L\'esprit méditerranéen au quotidien ! Structure à taille humaine où tout le monde se connaît. On soigne avec le cœur, et on déjeune en terrasse quand il fait beau.',
    leisure_activities: ['Plages', 'Voile', 'Œnotourisme', 'Marchés provençaux'],
    work_rhythm: ['Équilibré', 'Convivial'],
    perks: ['Ambiance familiale', 'Flexibilité', 'Investissement matériel', 'Esprit d\'équipe'],
    image_url: 'https://images.unsplash.com/photo-1632833239869-a37e3a5806d2?q=80&w=800&auto=format&fit=crop',
    video_url: 'https://www.youtube.com/watch?v=F_Sj8d94W2k',
  },
  {
    id: 'CER',
    name: 'Clinique du Vallespir',
    location: 'Céret (66)',
    region_vibe: 'Charme, ville d\'art, taille humaine',
    size: ['Familiale'],
    specialty_focus: ['Médecine', 'SSR', 'Court séjour'],
    bio: '🎨 Dans la ville des cerises et de Picasso ! Ici, l\'art de vivre catalan rencontre l\'excellence médicale. Petite structure, grande âme. Parfait pour ceux qui cherchent l\'authenticité.',
    leisure_activities: ['Musées', 'Festivals', 'Patrimoine', 'Randonnée'],
    work_rhythm: ['Posé', 'Culturel'],
    perks: ['Cadre de vie unique', 'Architecture', 'Vie culturelle riche', 'Proximité Espagne'],
    image_url: 'https://images.unsplash.com/photo-1519167758481-83f29da8c313?q=80&w=800&auto=format&fit=crop',
    video_url: 'https://www.youtube.com/watch?v=F_Sj8d94W2k',
  },
  {
    id: 'FLO',
    name: 'Clinique SMR Le Floride',
    location: 'Le Barcarès (66)',
    region_vibe: 'Les pieds dans l\'eau, cadre vacances',
    size: ['Moyenne'],
    specialty_focus: ['SSR', 'Rééducation fonctionnelle', 'Gériatrie'],
    bio: '🏖️ Littéralement les pieds dans l\'eau ! Nos patients se réveillent face à la mer. Vous aussi. Rééducation en mode vacances, mais avec toute la rigueur médicale qu\'on aime.',
    leisure_activities: ['Plage privée', 'Sports nautiques', 'Kitesurf', 'Détente balnéaire'],
    work_rhythm: ['Saisonnier', 'Détendu'],
    perks: ['Vue mer depuis les chambres', 'Cadre unique', 'Ambiance estivale', 'Activités nautiques'],
    image_url: 'https://images.unsplash.com/photo-1596178060671-7a80dc8059ea?q=80&w=800&auto=format&fit=crop',
    video_url: 'https://www.youtube.com/watch?v=F_Sj8d94W2k',
  },
  {
    id: 'SPV',
    name: 'Polyclinique Médipôle Saint-Roch',
    location: 'Cabestany (66)',
    region_vibe: 'Référence régionale, pluridisciplinaire, intense',
    size: ['Grande'],
    specialty_focus: ['Chirurgie', 'Urgences', 'Plateau technique complet', 'Toutes spécialités'],
    bio: '🚀 Le mastodonte du réseau ! Plateau technique de pointe, activité soutenue, équipes d\'experts. Si vous aimez l\'adrénaline médicale sous le soleil catalan, c\'est ici !',
    leisure_activities: ['Sport', 'Vie urbaine', 'Mer proche', 'Montagne accessible'],
    work_rhythm: ['Intense', 'Dynamique', 'Compétitif'],
    perks: ['Équipements de pointe', 'Toutes spécialités', 'Formation permanente', 'Carrière évolutive'],
    image_url: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?q=80&w=800&auto=format&fit=crop',
    video_url: 'https://www.youtube.com/watch?v=F_Sj8d94W2k',
  },
  {
    id: 'HPGN',
    name: 'Hôpital Privé du Grand Narbonne',
    location: 'Narbonne (11)',
    region_vibe: 'Dynamique, gros plateau technique, urgences',
    size: ['Grande'],
    specialty_focus: ['Urgences', 'Chirurgie', 'Médecine', 'Maternité'],
    bio: '⚡ Le cœur battant de l\'Aude ! Urgences 24/7, activité chirurgicale dense, maternité vivante. Pour ceux qui aiment avoir du rythme (et du rosé local après le service).',
    leisure_activities: ['Canal du Midi', 'Vignobles', 'Plages de Gruissan', 'Patrimoine romain'],
    work_rhythm: ['Soutenu', 'Urgences'],
    perks: ['Plateau complet', 'Service d\'urgences', 'Activité variée', 'Région viticole'],
    image_url: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?q=80&w=800&auto=format&fit=crop',
    video_url: 'https://www.youtube.com/watch?v=F_Sj8d94W2k',
  },
  {
    id: 'SUD',
    name: 'Clinique SMR Sud',
    location: 'Carcassonne (11)',
    region_vibe: 'Rééducation, historique, détente',
    size: ['Moyenne'],
    specialty_focus: ['SSR', 'Rééducation', 'Réadaptation'],
    bio: '🏰 À l\'ombre de la cité médiévale ! On soigne en douceur dans un cadre historique exceptionnel. Parfait équilibre entre professionnalisme et art de vivre du Sud-Ouest.',
    leisure_activities: ['Cité médiévale', 'Patrimoine UNESCO', 'Canal du Midi', 'Gastronomie'],
    work_rhythm: ['Équilibré', 'Patrimoine'],
    perks: ['Cadre historique', 'Qualité de vie exceptionnelle', 'Tourisme', 'Gastronomie réputée'],
    image_url: 'https://images.unsplash.com/photo-1571772996211-2f02c9727629?q=80&w=800&auto=format&fit=crop',
    video_url: 'https://www.youtube.com/watch?v=F_Sj8d94W2k',
  },
];
